package com.example.practica3

import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.google.android.material.button.MaterialButton
import com.google.android.material.textfield.TextInputEditText
import retrofit2.Call
import retrofit2.Callback
import retrofit2.Response

class AddProductActivity : AppCompatActivity() {

    private val apiService = ApiClient.retrofit.create(ApiService::class.java)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_add_product)

        val editTextTitle: TextInputEditText = findViewById(R.id.editTextTitle)
        val editTextPrice: TextInputEditText = findViewById(R.id.editTextPrice)
        val buttonSubmit: MaterialButton = findViewById(R.id.buttonSubmit)

        buttonSubmit.setOnClickListener {
            // Si no hay sesión, avisar y redirigir a Login
            if (!SessionManager.isLoggedIn) {
                Toast.makeText(this, "Debes iniciar sesión para añadir productos", Toast.LENGTH_SHORT).show()
                startActivity(Intent(this, LoginActivity::class.java))
                return@setOnClickListener
            }

            val title = editTextTitle.text?.toString().orEmpty()
            val priceString = editTextPrice.text?.toString().orEmpty()

            if (title.isNotEmpty() && priceString.isNotEmpty()) {
                val price = priceString.toDoubleOrNull() ?: 0.0
                val newProduct = Product(
                    productoId = null, // ID is null for a new product, since it's autogenerated by the server
                    productoNombre = title,
                    price = price,
                    imageUrl = "/images/default-product.jpg"
                )

                apiService.addProduct(newProduct).enqueue(object : Callback<Product> {
                    override fun onResponse(call: Call<Product>, response: Response<Product>) {
                        if (response.isSuccessful) {
                            Toast.makeText(this@AddProductActivity, "Producto añadido con éxito", Toast.LENGTH_SHORT).show()
                            finish()
                        } else {
                            Toast.makeText(this@AddProductActivity, "Error al añadir el producto: ${response.code()}", Toast.LENGTH_SHORT).show()
                            Log.e("ADD_PRODUCT", "Error: ${response.code()}")
                        }
                    }

                    override fun onFailure(call: Call<Product>, t: Throwable) {
                        Toast.makeText(this@AddProductActivity, "Error de conexión", Toast.LENGTH_SHORT).show()
                        Log.e("ADD_PRODUCT", "Failure: ${t.message}")
                    }
                })
            } else {
                Toast.makeText(this, "Por favor, rellena todos los campos", Toast.LENGTH_SHORT).show()
            }
        }
    }
}
